println("Enter a noun:")
noun  = strip(readline(STDIN))
println("Enter a verb:")
verb = strip(readline(STDIN))
println("Enter an adjective:")
adjective = strip(readline(STDIN))
println("Enter an adverb:")
adverb = strip(readline(STDIN))
println("You like to walk with $adjective $noun and you want to $verb $noun $adverb.")